In [17]:
# Exercício 8
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
colunas = ('sepallendth', 'sepalwidth', 'petallenght', 'petalwidth', 'species')

iris = np.genfromtxt(url, delimiter=',', dtype='object', encoding='ascii')

print(iris[:2])
print(iris[:2,0]) # Selecionar linha e coluna

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']]
[b'5.1' b'4.9']


In [1]:
# Exercício 9
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', encoding='ascii')

species = iris[:, 4].astype(str)
print(species)


['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [16]:
# Exercício 10
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', encoding='ascii')

sepallendth = iris[:, 0].astype(float)

print(f'Média: {np.mean(sepallendth):.2f} - Mediana: {np.median(sepallendth):.2f} - Desvio Padrão: {np.std(sepallendth):.2f}')


Média: 5.84 - Mediana: 5.80 - Desvio Padrão: 0.83


In [20]:
# Exercício 11
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', encoding='ascii')

sepallendth = iris[:, 0].astype(float)

valor_maximo = np.max(sepallendth)
valor_minimo = np.min(sepallendth)

print(f'Maximo = {valor_maximo} - Minimo = {valor_minimo}')

sepallendth = (sepallendth - valor_minimo) / (valor_maximo - valor_minimo)
print(sepallendth)

Maximo = 7.9 - Minimo = 4.3
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.

In [28]:
# Exercício 12
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', encoding='ascii')

sepallendth = iris[:, 0].astype(float)

print(f' O 5º percentil é: {np.percentile(sepallendth, 5):.2f} e ó 95° Percentil é: {np.percentile(sepallendth, 95):.2f}')

print(f'Vetor Percentil: {np.percentile(sepallendth, q=[5, 95])}')


 O 5º percentil é: 4.60 e ó 95° Percentil é: 7.25
Vetor Percentil: [4.6   7.255]


In [41]:
# Exercício 13
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size= 20), np.random.randint(4, size = 20)] = np.nan

sepallendth = iris_2d[:, 0].astype(float)

print(f'Quantidade de Valores Ausentes: {np.isnan(sepallendth).sum()}')
print(f'Posição dos Valores Ausentes: {np.where(np.isnan(sepallendth))}')


Quantidade de Valores Ausentes: 5
Posição dos Valores Ausentes: (array([ 15,  77, 116, 135, 144], dtype=int64),)


In [3]:
# Exercício 14
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3], encoding='ascii')

condicao = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condicao]


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [12]:
# Exercício 15
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3], encoding='ascii')
iris_2d[np.random.randint(150, size= 20), np.random.randint(4, size = 20)] = np.nan

any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [15]:
# Exercício 16
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')

print(f'A correlação é: {np.corrcoef(iris_2d[:, 0].astype(float), iris_2d[:, 2].astype(float))[1:2,0]}')

A correlação é: [0.87175416]


In [32]:
# Exercício 17

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condicao = np.isnan(iris_2d)
if True in condicao:
    print(f'True')
else:
    print(f'False')


False


In [34]:
# Exercício 18
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print(np.nan_to_num(iris_2d))

[[5.1 3.5 0.  0.2]
 [0.  3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0. ]
 [4.8 3.  1.4 0.1]
 [0.  3.  0.  0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [0.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [35]:
# Exercício 19
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

valores_unicos = set(iris[:,4])

print(valores_unicos)

{b'Iris-versicolor', b'Iris-setosa', b'Iris-virginica'}


In [1]:
# Exercício 20
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

dt = iris[:,2].astype(float)
np.place(dt , dt  > 5, 5)
np.place(dt , dt  < 3, 6)
np.place(dt , dt  < 5, 4)

dt = dt.astype(str)

dt  = np.where(dt == '5.0','Grande', dt)
dt  = np.where(dt == '6.0','Pequena', dt)
dt  = np.where(dt == '4.0','Média', dt)

print(dt)


['Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena' 'Pequena'
 'Pequena' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média'
 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média'
 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média'
 'Média' 'Grande' 'Média' 'Média' 'Média' 'Média' 'Média' 'Grande' 'Média'
 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Média'
 'Média' 'Média' 'Média' 'Média' 'Média' 'Média' 'Grande' 'Grande'
 'Grande' 'Grande' 'Grande' 'Grande' 'Média' 'Grande' 'Grande' 'Gra

In [3]:
# Exercício 21
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

volume = (np.pi * iris_2d[:, 2].astype(float) * iris_2d[:, 0].astype(float) ** 2)/3

print(volume)

[ 38.13265163  35.20049849  30.07237208  33.23805027  36.65191429
  51.91167701  31.02218026  39.26990817  28.38324243  37.71481981
  45.80442089  38.60389053  33.77840421  21.29895099  42.27327075
  51.03517266  39.69716477  38.13265163  57.83986235  40.85641246
  51.91167701  40.85641246  22.15870018  46.30393412  45.84212
  41.88790205  41.88790205  42.47433268  39.6427105   37.01215025
  38.60389053  45.80442089  42.47433268  44.34881629  37.71481981
  31.41592654  41.1810437   37.71481981  26.35586797  40.85641246
  34.03392041  27.56747554  26.35586797  41.88790205  51.75145578
  33.77840421  43.58017329  31.02218026  44.12366882  36.65191429
 241.16959604 193.01945264 244.29966952 126.71090369 203.52284408
 153.10551797 195.34737279  82.97260357 209.83325652 110.43326496
  91.62978573 153.10237638 150.79644737 183.14123814 118.22441474
 206.83827152 147.78051842 144.43367505 181.14423241 128.0764493
 174.97414443 155.86488352 203.66002695 183.14123814 184.4408103
 200.71007145 2

In [5]:
# Exercício 22
import numpy as np


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object', usecols=[2, 4])
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sertosa = (iris[iris[:, 1]==b'Iris-setosa'])[:, 0]
sertora_segundo_maior = np.sort(sertosa)[-2]

print(sertora_segundo_maior)


b'1.9'


In [6]:
# Exercício 23

import numpy as np


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[:,0] = iris[:, 0].astype(float)

iris.sort(axis=0)

print(iris)

[[4.3 b'2.0' b'1.0' b'0.1' b'Iris-setosa']
 [4.4 b'2.2' b'1.1' b'0.1' b'Iris-setosa']
 [4.4 b'2.2' b'1.2' b'0.1' b'Iris-setosa']
 [4.4 b'2.2' b'1.2' b'0.1' b'Iris-setosa']
 [4.5 b'2.3' b'1.3' b'0.1' b'Iris-setosa']
 [4.6 b'2.3' b'1.3' b'0.1' b'Iris-setosa']
 [4.6 b'2.3' b'1.3' b'0.2' b'Iris-setosa']
 [4.6 b'2.3' b'1.3' b'0.2' b'Iris-setosa']
 [4.6 b'2.4' b'1.3' b'0.2' b'Iris-setosa']
 [4.7 b'2.4' b'1.3' b'0.2' b'Iris-setosa']
 [4.7 b'2.4' b'1.3' b'0.2' b'Iris-setosa']
 [4.8 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.8 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.8 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.8 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.8 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.9 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.9 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.9 b'2.5' b'1.4' b'0.2' b'Iris-setosa']
 [4.9 b'2.6' b'1.4' b'0.2' b'Iris-setosa']
 [4.9 b'2.6' b'1.4' b'0.2' b'Iris-setosa']
 [4.9 b'2.6' b'1.4' b'0.2' b'Iris-setosa']
 [5.0 b'2.6' b'1.4' b'0.2' b'Iris-setosa']
 [5.0 b'2.6

In [4]:
# Exercício 24
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
nomes = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petallength = iris[:,2]

unicos, contador = np.unique(petallength, return_counts=True)

index_maior = np.argmax(contador)

print(f'O Valor mais frequênte da coluna petallength é {unicos[index_maior]} com um total de {contador[index_maior]} repetições')


O Valor mais frequênte da coluna petallength é b'1.5' com um total de 14 repetições


In [23]:
# Exercício 25
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
petalwidth = iris[:,3].astype(float)

resposta = np.where(petalwidth > 1.0)

print(f'A primeira posição de um valor maior que 1.0 é a {resposta[0][0]}ª')

A primeira posição de um valor maior que 1.0 é a 50ª


In [13]:
# Exercício 26
import numpy as np

np.random.seed(100)
vetor = np.random.uniform(1,50, 20)
vetor.sort()
print(vetor[:(len(vetor)-6):-1])

[48.95256545 44.67477576 42.39403048 41.466785   40.99501269]


In [15]:
# Exercício 27
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

sertosa = (iris[iris[:, 4]==b'Iris-setosa'])[:, 0].astype(float)
virginica = (iris[iris[:, 4]==b'Iris-virginica'])[:, 0].astype(float)
versicolor = (iris[iris[:, 4]==b'Iris-versicolor'])[:, 0].astype(float)

print(f'Média de Sepallength na espécie Sertosa: {sertosa.mean():.2f}')
print(f'Média de Sepallength na espécieVirginica: {virginica.mean():.2f}')
print(f'Média de Sepallength na espécieVersicolor: {versicolor.mean():.2f}')

Média de Sepallength na espécie Sertosa: 5.01
Média de Sepallength na espécieVirginica: 6.59
Média de Sepallength na espécieVersicolor: 5.94
